[문의 페이지] 댓글 수정,삭제
Liberty52/front-end pull request #316
Opened 2023-11-20 16:03 UTC by jungyeons

# [문의 페이지] 댓글 수정, 삭제
 특장점 (각자의 댓글만 수정할 수 있다. 상대의 댓글은 수정할 수 없다.)
 < 수정 영상 >

https://github.com/Liberty52/front-end/assets/81145288/72a84463-c502-406c-a8c2-0e6006d625ef

< 삭제 영상 >

https://github.com/Liberty52/front-end/assets/81145288/dbeb6b6f-7a53-4928-bd7b-cdccf69a0b04

2023-11-20 16:39 UTC, heeeione requested changes
![image](https://github.com/Liberty52/front-end/assets/68272931/d1568963-5d17-4cf4-93cd-2e571a57a77e)

수정 / 삭제가 날짜보다 조금 더 위에 있는 것 같아서 같은 행에 위치해 있으면 보기 좋을 것 같습니다

2023-11-20 16:39 UTC, heeeione commented on src/axios/support/Notice.js
> +  const data = { content: content };
patch 인자로 content를 바로 안 넘기고 data 변수에 할당한 이유가 궁금합니다

2023-11-20 16:39 UTC, heeeione commented on src/component/support/NoticeComment.js
> +      alert('잘못된 요청입니다');
잘못된 요청이라 하면 사용자 입장에선 뭐가 잘못 됐는지 모를 수 있으니까 그냥 빼거나 자세하게 적어주면 좋겠습니다

2023-11-20 16:39 UTC, heeeione commented on src/component/support/NoticeComment.js
> +          {comment.mine ? (
comment.mine ? () : (null) 보단 comment.mine && () 이 조금 더 좋아보입니다

2023-11-20 16:39 UTC, heeeione commented on src/component/support/NoticeComment.js
> +            <div style={{ display: 'flex', gap: '5px', marginLeft: '15px' }}>
style은 styled component로 작성하는 편이 좋습니다

2023-11-20 17:57 UTC, jungyeons commented
> ![image](https://user-images.githubusercontent.com/68272931/284332571-d1568963-5d17-4cf4-93cd-2e571a57a77e.png)
> 
> 수정 / 삭제가 날짜보다 조금 더 위에 있는 것 같아서 같은 행에 위치해 있으면 보기 좋을 것 같습니다

< 높이 조절 완료 >
![높이 조절완료](https://github.com/Liberty52/front-end/assets/81145288/95d3ddba-0802-465c-9dc7-c20faaad1639)
완료요~

2023-11-20 18:11 UTC, jungyeons commented
< 수정 파일 위치 >
![수정 파일 위치1](https://github.com/Liberty52/front-end/assets/81145288/42d0b2b0-f25c-4f7d-95c7-313eb1e3499b)
![수정 파일 위치2](https://github.com/Liberty52/front-end/assets/81145288/e4394d42-5dbb-44dd-b637-f9cb247a5c76)

2023-11-21 06:13 UTC, 2hanbyeol1 commented on src/axios/support/Notice.js
> +  const data = { content: content };
content만 쓰면 오류나지 않나?

2023-11-21 06:20 UTC, 2hanbyeol1 requested changes
<img width="500" alt="image" src="https://github.com/Liberty52/front-end/assets/78421872/f0242a2b-3d6f-4739-b855-c17894b17b73">

- 수정 취소 대신에 '취소' 두 글자가 더 깔끔할 것 같습니다.
- 수정 취소 왼쪽에 마진이 있었으면 좋겠습니다.

- 수정 모드일 때는 수정 삭제 버튼이 없어졌으면 좋겠습니다.

- Input에도 css가 필요해보입니다...............

2023-11-21 06:41 UTC, heeeione commented on src/axios/support/Notice.js
> +  const data = { content: content };
무슨 오류?

2023-11-21 07:43 UTC, 2hanbyeol1 commented on src/axios/support/Notice.js
> +  const data = { content: content };
정확히는 까먹었는데 객체로 줘야할 걸...............?????

2023-11-21 10:19 UTC, jungyeons commented
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/78421872/284480588-f0242a2b-3d6f-4739-b855-c17894b17b73.png">
> * 수정 취소 대신에 '취소' 두 글자가 더 깔끔할 것 같습니다.
> * 수정 취소 왼쪽에 마진이 있었으면 좋겠습니다.
> * 수정 모드일 때는 수정 삭제 버튼이 없어졌으면 좋겠습니다.
> * Input에도 css가 필요해보입니다...............
마진 넣었습니다.
input.css가 필요해보인다고 하시는데 댓글 작성할 때 input.css 그대로 가져다 쓰고 있어요.

2023-11-21 10:29 UTC, jungyeons commented
애초에 로직이 문제가 있던 코드가 아니고 리뷰해주신 것 모두 문법을 이렇게 하지말고 이렇게 하는 게 더 좋을것 같다 혹은 스타일 관련 리뷰고
문법 관련해서 불편하다고 한 거 전부 고쳤습니다. 스타일은 최대한 고쳐달라는 것 다 고쳤고요. 
로직 상의 문제가 없으면 approve하고 스타일의 부차적인 요구는 데모 후에 다양한 사람들 의견을 듣고 고치는 게 낫다고 생각합니다.

2023-11-21 10:33 UTC, 2hanbyeol1 approved these changes

2023-11-21 11:20 UTC, merged