Fix Error about add cart (License & Custom Products)
Liberty52/front-end pull request #323
Opened 2023-11-28 07:53 UTC by Autumn-Rainfall

2023-11-28 15:01 UTC, heeeione requested changes

2023-11-28 15:01 UTC, heeeione commented on src/component/order/OrderOptions.js
> +        licenseOptionId: img.id,
이거 바꾼 이유 있음??
이거 바꾸면 아마 그냥 결제 안 될텐데

2023-11-29 02:37 UTC, Autumn-Rainfall commented on src/component/order/OrderOptions.js
> +        licenseOptionId: img.id,
서버에서 요청하는 이름이 저렇게 되어있음.. 백엔드 분들이 파라미터명 통일을 안해주셨나보네

2023-11-29 03:10 UTC, heeeione requested changes

2023-11-29 03:10 UTC, heeeione commented on src/component/order/OrderOptions.js
> +        licenseOptionId: img.id,
일단 통일되면 머지하자 내가 얘기할게

2023-12-01 18:06 UTC, Autumn-Rainfall reviewed
수정함 급하게 하느라 코드 좀 지저분한데 APPROVE, 머지까지 부탁함 @heeeione

2023-12-02 02:21 UTC, heeeione approved these changes

2023-12-02 02:22 UTC, merged